### ISSUE TITLE
Vendor data present

### ISSUE THREAD

**Issue by mensfeld** [tf0101/VideoChatGet#73]
Hey there,

My name is Maciej Mensfeld and I run security & quality assessments for Ruby libraries using Diffend.io.

While reviewing the changes for this lib, I noticed, that the vendor directory is being included in the RubyGems releases.

Is this needed? Usually, it's added by mistake and causes:

a) confusion
b) problems when tracking changes
c) extensive library size

ref: https://my.diffend.io/gems/video_chat_get//0.1.0/page/70#d2h-125995

If the presence of vendor data is valid I would love the reasoning. Thanks!

**Comment by tf0101** [comment]
Thanks for contacting me.
The vendor directory was not needed.
So I did the following two things.

・The vendor directory is no longer tracked by Git. #74
・We have released a gem that does not include the vendor directory. #76


The vendor directory should now be excluded from RubyGems releases.

**Comment by mensfeld** [comment]
Thank you. The change is amazing: 99% size reduction :)
